language: ruby
rvm: 2.7.0
sudo: false
cache: bundler
bundler_args: --without production
env:
  global:
    - CC_TEST_REPORTER_ID=bc3522c31226680d254991d9453696b344ff01336222f0fab32de2278dcf4dac
    - CCTR=/tmp/cc-test-reporter
before_install:
  - ruby --version
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v 2.1.4
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > $CCTR
  - chmod +x $CCTR
  - $CCTR before-build
  - gem update --system
script:
  - bundle exec rake db:setup
  - bundle exec rake spec
#   - $CCTR format-coverage -t simplecov -o coverage/codeclimate.$SUITE.json
  - bundle exec rake cucumber
#   - $CCTR format-coverage -t simplecov -o coverage/codeclimate.$SUITE.json
after_script:
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter format-coverage -t simplecov -o ./coverage/codeclimate.$CI_NODE_INDEX.json ./coverage/spec/.resultset.json; fi
#   - $CCTR sum-coverage coverage/codeclimate.*.json | $CCTR upload-coverage
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter sum-coverage --output - --parts $CI_NODE_TOTAL coverage/codeclimate.*.json | ./cc-test-reporter upload-coverage --input -; fi
  - $CCTR after-build --exit-code $TRAVIS_TEST_RESULT